# Config for mapping keyboard keys to joystick axes and buttons

axes:
  # Axis mappings: Define which keyboard keys control specific joystick axes
  # Format: '<key>: [<axis_index>, <axis_value>, <mode>'
  # normal' mode: axis value updates momentarily based on key press
  # 'sticky' mode: axis value remains at the last set value until changed
  # example  Key.down: [2, -1.0, 'sticky']

  w: [1, -1.0, 'normal'] 
  s: [1, 1.0, 'normal'] 
  a: [0, -1.0, 'normal']
  d: [0, 1.0, 'normal']
  Key.up: [3, -1.0, 'normal']   
  Key.down: [3, 1.0, 'normal']
  Key.left: [2, -1.0, 'normal']
  Key.right: [2, 1.0, 'normal']

# Parameters for axis increment_rate, increment_step
parameters:
  axis_increment_rate: 0.01   # Time interval for updating axis values
  axis_increment_step: 0.01   # Step size for axis value change

buttons:
  # Button mappings: Define which keyboard keys toggle specific joystick buttons
  # Format: '<key>: <button_index>'
  '3': 1 
  '4': 2 
  '2': 3 
  '0': 4 
  '1': 9
