# Controller manager configuration
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    # use_sim_time: true
    effort_controllers:
      type: effort_controllers/JointGroupEffortController
    # Declare controller name and type
    hector_controller:
      type: hector_controller/HectorController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      use_local_topics: true

    gazebo_joint_controller:
      type: forward_command_controller/ForwardCommandController      

# Properties of the custom controler and definition of joints to use
hector_controller:
  ros__parameters:
    joints:
      - L_hip_yaw_joint
      - L_hip_roll_joint
      - L_hip_pitch_joint
      - L_knee_joint
      - L_ankle_joint
      - R_hip_yaw_joint
      - R_hip_roll_joint
      - R_hip_pitch_joint
      - R_knee_joint
      - R_ankle_joint
      - L_shoulder_yaw_joint
      - L_shoulder_pitch_joint
      - L_shoulder_roll_joint
      - L_elbow_joint
      - R_shoulder_yaw_joint
      - R_shoulder_pitch_joint
      - R_shoulder_roll_joint
      - R_elbow_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

